export function createHud(controls){
  document.body.insertAdjacentHTML('beforeend',`<div id="crosshair"></div><div id="overlay" class="screen"><div class="card hero"><span class="eyebrow">NEON OUTPOST</span><h1>ARENA <b>PROTOCOL</b></h1><p>Survive escalating waves. Collect weapons. Defeat the boss.</p><div class="settings"><label>Difficulty <select id="difficulty"><option value=".8">Recruit</option><option value="1" selected>Operative</option><option value="1.3">Veteran</option></select></label><label>Sensitivity <input id="sensitivity" type="range" min=".3" max="2" value="1" step=".1"></label><label>Volume <input id="volume" type="range" min="0" max="1" value=".7" step=".1"></label><label>Graphics <select id="graphics"><option value="1">Performance</option><option value="1.5" selected>Balanced</option><option value="2">High</option></select></label></div><button id="playbtn">DEPLOY</button><div class="controls">WASD Move · Mouse Aim · Click Fire · R Reload · 1–4 Weapons · Shift Sprint · Space Jump · P Pause</div></div></div><div id="hud"><div class="hudtop"><div><small>SCORE</small><strong id="score">0</strong><em id="best">BEST 0</em></div><div id="wave">WAVE 1</div><div id="nethud2">OFFLINE</div></div><div id="boss"><label>BOSS</label><div><i id="bossbar"></i></div></div><div id="feed"></div><div class="hudbottom"><div class="healthpanel"><small>VITALS</small><div id="healthwrap"><i id="healthbar"></i><b id="healthtext">100</b></div></div><div class="weaponpanel"><small id="weaponname">PISTOL</small><b id="ammo">12</b><span id="reserve">/ 72</span></div></div></div><div id="damageflash"></div><div id="modal" class="screen hidden"><div class="card" id="modalcard"></div></div>`);
  const mission=document.createElement('div');mission.id='mission';mission.innerHTML='<small>ACTIVE MISSION</small><b id="missionlabel">Eliminate hostiles</b><span id="missionprogress">0 / 10</span>';document.body.appendChild(mission);
  const $=id=>document.getElementById(id),overlay=$('overlay'),hud=$('hud'),modal=$('modal');
  $('playbtn').onclick=e=>{e.stopPropagation();controls.lock();};
  controls.addEventListener('lock',()=>{overlay.classList.add('hidden');hud.classList.remove('hidden');if(!modal.dataset.keep)modal.classList.add('hidden');});
  controls.addEventListener('unlock',()=>{if(modal.classList.contains('hidden'))overlay.classList.remove('hidden');hud.classList.add('hidden');});
  const wire=actions=>document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>actions[b.dataset.action]?.());
  const api={
    onSettings(cb){['difficulty','sensitivity','volume','graphics'].forEach(id=>$(id).addEventListener('input',()=>cb(id,Number($(id).value))));},
    setWeapon(name,ammo,reserve){$('weaponname').textContent=name.toUpperCase();$('ammo').textContent=ammo;$('reserve').textContent=`/ ${reserve}`;},setReloading(v){if(v)$('ammo').textContent='···';},
    setHealth(h,m){$('healthbar').style.width=Math.max(0,h/m*100)+'%';$('healthtext').textContent=Math.ceil(h);},setScore(v){$('score').textContent=v.toLocaleString();},setBest(v){$('best').textContent=`BEST ${v.toLocaleString()}`;},setWave(v){$('wave').textContent=`WAVE ${v}`;},setMission(label,value,target){$('missionlabel').textContent=label;$('missionprogress').textContent=`${value} / ${target}`;},
    setBoss(h,m,show){$('boss').style.display=show?'block':'none';$('bossbar').style.width=Math.max(0,h/m*100)+'%';},damageFlash(){$('damageflash').classList.add('active');setTimeout(()=>$('damageflash').classList.remove('active'),160);},
    toast(t,type='info'){const e=document.createElement('div');e.className=`toast ${type}`;e.textContent=t;$('feed').appendChild(e);setTimeout(()=>e.remove(),2800);},setNetwork(t){$('nethud2').textContent=t;},
    showUpgrade(cb){modal.dataset.keep='1';modal.classList.remove('hidden');$('modalcard').innerHTML='<span class="eyebrow">WAVE CLEARED</span><h2>CHOOSE AN UPGRADE</h2><div class="choices"><button data-action="damage">+15% DAMAGE</button><button data-action="reload">FASTER RELOAD</button><button data-action="magazine">+4 MAGAZINE</button><button data-action="health">+20 MAX HEALTH</button></div>';wire({damage:()=>cb('damage'),reload:()=>cb('reload'),magazine:()=>cb('magazine'),health:()=>cb('health')});},hideUpgrade(){delete modal.dataset.keep;modal.classList.add('hidden');},
    showPause(show,resume,restart){if(!show){delete modal.dataset.keep;modal.classList.add('hidden');return;}modal.dataset.keep='1';modal.classList.remove('hidden');$('modalcard').innerHTML='<h2>PAUSED</h2><button data-action="resume">RESUME</button><button class="secondary" data-action="restart">RESTART RUN</button>';wire({resume,restart});},
    showGameOver(score,wave,restart){modal.dataset.keep='1';modal.classList.remove('hidden');$('modalcard').innerHTML=`<span class="eyebrow danger">MISSION FAILED</span><h2>YOU FELL ON WAVE ${wave}</h2><p>Final score <b>${score.toLocaleString()}</b></p><button data-action="restart">RUN AGAIN</button>`;wire({restart});},
    reset(){api.setScore(0);api.setHealth(100,100);api.setBoss(0,1,false);delete modal.dataset.keep;modal.classList.add('hidden');}
  };return api;
}
